version: '3.4'
name: inventory-backend

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Inventory.API/Dockerfile
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_started
    networks:
        - inventory-net
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: tH1s1Sp0str3Sp@ssW0rd!!!
    ports:
      - "5432:5432"
    networks:
        - inventory-net
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
        - inventory-net
networks:
    inventory-net:
